apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-experiments
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests
    repoURL: 'git@github.com:daftping/tmp2.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
